version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  build:
    commands:
      - docker build -t everydayrails .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI
  post_build:
    commands:
      - docker push $REPOSITORY_URI
      - echo "[{\"name\":\"${IMAGE_REPO_NAME}\",\"imageUri\":\"${REPOSITORY_URI}\"}]" >imagedefinitions.json
artifacts:
  files: imagedefinitions.json
